### PR TITLE
Crc uuid

### PR DESCRIPTION
**Pull request by ansondtx20**
Second patch for UUID based MAC

https://github.com/ARMmbed/mbed-hal-k64f/pull/24

### CODE REVIEW

**Comment by sg-** [comment]
Just an FYI - This patch should propagate further up into common code. Any board using UUID for MAC address (not ideal at all) will need these, not just NXP targets.

**Comment by bridadan** [comment]
This is a pretty critical fix, can we get this moving? This PR needs to be merged first though: https://github.com/ARMmbed/mbed-hal-k64f/pull/24

**Comment by 0xc0170** [comment]
@bogdanm @bremoran to be aware of this mac address issue. As Sam noted above, this might require to move to upper layer somewhere.

**Comment by bremoran** [comment]
Do we really need CRC for this? I know it's not ideal, but could we do this instead?

```C
void mbed_mac_address(char *mac)
{
    uint32_t UUID_LOC_BASE = 0x40048054;    // First adddress of the 4-word UUID
    uint32_t uuid[4];                          // So we can take a local copy of the UUID
    uint32_t MAC[3];                        // 3 16 bits words for the MAC

    // copy the UUID to the variable MAC[]
    memcpy(uuid, (const void *)UUID_LOC_BASE, sizeof(uuid));    
        
    // The network stack expects an array of 6 bytes
    // so we copy, and shift and copy from the half-word array to the byte array
    srand(uuid[0] ^ uuid[1] ^ uuid[2] ^ uuid[3]);
    mac[0] = rand() & 0xFF;
    mac[1] = rand() & 0xFF;
    mac[2] = rand() & 0xFF;
    mac[3] = rand() & 0xFF;
    mac[4] = rand() & 0xFF;
    mac[5] = rand() & 0xFF;
    // We want to force bits [1:0] of the most significant byte [0]
    // to be "10" 
    // http://en.wikipedia.org/wiki/MAC_address
    mac[0] |= 0x02; // force bit 1 to a "1" = "Locally Administered"
    mac[0] &= 0xFE; // force bit 0 to a "0" = Unicast
}
```

**Comment by sg-** [comment]
The MAC cant be random for a board over time. It needs to be consistent and a known how its calculated (IBM quickstart for example).

**Comment by kjbracey-arm** [comment]
That assumes the top 4 bytes vary between boards. I don't see anything in the docs about how the UUID is generated, so I think it's correct to use all 16 bytes as input.

(And the way you've written it limits it to 2^8 addresses - even if the srand is corrected, it's limited to 2^31).

**Comment by bremoran** [comment]
Is there an adequate interim solution that we can use until we have a chance to get CRC into the codebase?

**Comment by sg-** [comment]
Not that I can think of. The proposed CRC solution has been in place for nearly a year now in mbed Classic so its not a new thing.

**Comment by kjbracey-arm** [comment]
CRC seems a little heavyweight, but if you're pulling in the code for some other reason, why not?

A lighter alternative that springs to mind for this application is the FNV-1a hash:

https://en.wikipedia.org/wiki/Fowler-Noll-Vo_hash_function

Could be just a few lines.

**Comment by 0xc0170** [comment]
@ansondtx20 @sg- We should fix this warnings ! I'll create a tracking issue for this, and try to fix it now, will create a new PR to address this

```
[127/130] Building C object ym/mbed-hal-frdm-k64f/source/CMakeFiles/...repo/github/yotta_thing/mbed-hal-frdm-k64f/source/mbed_overrides.c.o C:/Code/git_repo/github/yotta_thing/mbed-hal-frdm-k64f/source/mbed_overrides.c: In function 'mbed_mac_address':
C:/Code/git_repo/github/yotta_thing/mbed-hal-frdm-k64f/source/mbed_overrides.c:45:5: warning: implicit declaration of function 'memcpy' [-Wimplicit-function-declaration]
     memcpy(uuid, (const void *)UUID_LOC_BASE, sizeof(uuid));
     ^
C:/Code/git_repo/github/yotta_thing/mbed-hal-frdm-k64f/source/mbed_overrides.c:45:5: warning: incompatible implicit declaration of built-in function 'memcpy'
C:/Code/git_repo/github/yotta_thing/mbed-hal-frdm-k64f/source/mbed_overrides.c:48:22: warning: pointer targets in passing argument 1 of 'crcSlow' differ in signedness [-Wpointer-sign]
     MAC[0] = crcSlow(uuid, 8);  // most significant half-word
                      ^
In file included from C:/Code/git_repo/github/yotta_thing/mbed-hal-frdm-k64f/source/mbed_overrides.c:19:0:
C:/Code/git_repo/github/yotta_thing/example-mbedos-blinky/yotta_modules/mbed-hal-k64f/mbed-hal-k64f/crc.h:76:7: note: expected 'const unsigned char *' but argument is of type 'char *'
 crc   crcSlow(unsigned char const message[], int nBytes);
       ^
C:/Code/git_repo/github/yotta_thing/mbed-hal-frdm-k64f/source/mbed_overrides.c:49:22: warning: pointer targets in passing argument 1 of 'crcSlow' differ in signedness [-Wpointer-sign]
     MAC[1] = crcSlow(uuid, 12);
                      ^
In file included from C:/Code/git_repo/github/yotta_thing/mbed-hal-frdm-k64f/source/mbed_overrides.c:19:0:
C:/Code/git_repo/github/yotta_thing/example-mbedos-blinky/yotta_modules/mbed-hal-k64f/mbed-hal-k64f/crc.h:76:7: note: expected 'const unsigned char *' but argument is of type 'char *'
 crc   crcSlow(unsigned char const message[], int nBytes);
       ^
C:/Code/git_repo/github/yotta_thing/mbed-hal-frdm-k64f/source/mbed_overrides.c:50:22: warning: pointer targets in passing argument 1 of 'crcSlow' differ in signedness [-Wpointer-sign]
     MAC[2] = crcSlow(uuid, 16); // least significant half word
                      ^
In file included from C:/Code/git_repo/github/yotta_thing/mbed-hal-frdm-k64f/source/mbed_overrides.c:19:0:
C:/Code/git_repo/github/yotta_thing/example-mbedos-blinky/yotta_modules/mbed-hal-k64f/mbed-hal-k64f/crc.h:76:7: note: expected 'const unsigned char *' but argument is of type 'char *'
 crc   crcSlow(unsigned char const message[], int nBytes);
```

**Comment by 0xc0170** [comment]
#18 addressed the comment above

**Pull request merged**
