### PR TITLE
Revert "Remove PinNames.h, since it is now superseded"

### PR DESCRIPTION
**Pull request by 0xc0170**
Reverts ARMmbed/mbed-hal-frdm-k64f#9

Version 0.4.5 breaks some examples, this PR reverts the changeset, do a new release v0.4.6. Then to resend this and do a new v0.5.0 for this module? 
The upper module - mbed-hal-k64f is already v0.4.x ,where this is fixed (one more PR waiting to be merged for PinName to be included via extraIncludes). Another possilibity is  we could do v0.3.x patch to get fixes from v0.4.x.This reverting seems to be better option. 

What do you think?

@bremoran @bogdanm

### CODE REVIEW

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by bremoran** [comment]
-1.  This is handled by https://github.com/ARMmbed/mbed-hal-k64f/pull/20

**Comment by bremoran** [comment]
@0xc0170 This will create a very confusing git history.  Instead, it is better to create a branch called v0.4, and do the revert there.

**Comment by 0xc0170** [comment]
>  This is handled by ARMmbed/mbed-hal-k64f#20

It is but not for the version which we need. That one will be merged to master which is now 0.4.x as pointed out above. @bremoran try to build any example, and send a patch to mbed-hal-k64f, to earlier version which needs it. I'll close then this PR

**Comment by 0xc0170** [comment]
OK patch created, fixed

**Pull request closed without merging**
